config/routes.rb
Rails.application.routes.draw do
  get "welcome/index"

  devise_for :admins
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "welcome#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "TripleG" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <!-- Bootstrap CSS v5.2.1 -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
      <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
  
  </head>

  <body>

    <header>
        <%= render "shared/logged_navbar" if user_signed_in?%>
        <%= render "shared/general_navbar" if !user_signed_in?%>
    </header>

    <%= render "shared/left_side"%>
    
    <main>
      <%= render "shared/notice_alert"%>
      <%= yield %>
    </main>
    <%= render "shared/right_side"%>
    
    <%= render "shared/footer"%>
    
    <!-- Bootstrap JavaScript Libraries -->
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
      integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
      crossorigin="anonymous"
    ></script>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
      integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
      crossorigin="anonymous"
    ></script>
    
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="container-fluid shadow"> 
    <div class="d-flex">
        <span class="w-100 text-center display-6 fs-6">&copy; Plantillar TripleG, 2024</span>
    </div>
    <div class="d-flex justify-content-center gap-3 mb-0">
        <i class="bi bi-github fs-3"></i>
        <i class="bi bi-patch-question fs-3"></i>
    </div>
</footer>

app/views/shared/_general_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-light px-2" data-turbo-permanent>
    <!-- Brand -->
            <%= link_to "Navbar", root_path, class:"navbar-brand" %>
            <button class="navbar-toggler d-lg-none ms-auto" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavId" aria-controls="collapsibleNavId" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        <!---->
        <div class="collapse navbar-collapse" id="collapsibleNavId">
            <ul class="navbar-nav w-100">
               <li class="nav-item">
                    <%= link_to "Main",  '#' , class:"nav-link"%>
                </li>

            </ul>
        
        </div>    

</nav>

app/views/shared/_h1_title.html.erb
<section class="d-inline-flex align-items-center m-0 p-0 mb-5">
    <%= link_to :back, class:"btn btn-outline-primary ms-2 border-0" do%><i class="bi bi-arrow-left"></i><%end%>
    <h1 class="display-3 ms-5 px-3"><%= title %></h1>
</section> 

app/views/shared/_left_side.html.erb
<aside id="leftSide">
    left
</aside>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-light px-2" data-turbo-permanent>
    <!-- Brand -->
            <%= link_to "Navbar", root_path, class:"navbar-brand" %>
            <button class="navbar-toggler d-lg-none ms-auto" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavId" aria-controls="collapsibleNavId" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        <!---->
        <div class="collapse navbar-collapse" id="collapsibleNavId">
            <ul class="navbar-nav w-100">
            <!-- admin menu -->
                <% if current_user&.admin? %>
                <li class="nav-item">
                    <%= link_to "Dashboard",  admin_dashboard_path, class:"btn btn-success p-1"%>
                </li>
                <%end%>
            <!-- end admin menu -->
                <li class="nav-item">
                    <%= link_to "See the offers",  joboffers_path, class:"nav-link"%>
                </li>

                <li class="d-md-none nav-item dropdown mb-2">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdownId" data-bs-toggle="dropdown" aria-haspopup="true"aria-expanded="false">
                        <strong>@<%= current_user&.name || current_user&.email %></strong>
                    </a>
                    <div class="dropdown-menu mx-0 p-0" aria-labelledby="dropdownId">
                        <%= link_to "My profile", current_user.admin == true ? admin_user_path(current_user) : user_path(current_user),class:"dropdown-item" %>
                        
                        <%= link_to "My applies", user_applications_path(current_user), class:"dropdown-item" unless current_user.admin == true %>
                    </div>
                </li>
                
                <div class="dropdown-divider"></div>
                
                <li class="nav-item me-auto">
                    <%= button_to 'Sign out', destroy_user_session_path, method: :delete, class:"btn btn-primary" %>
                </li>

            </ul>
        
        </div>    

</nav>

app/views/shared/_notice_alert.html.erb
      <div class="d-flex p-0 m-1">
        <% if flash[:notice] %>
            <div class="alert alert-success" role="alert">
                <%= flash[:notice] %>
            </div>
        <% end %>

        <% if flash[:alert] %>
            <div class="alert alert-danger" role="alert">
                <%= flash[:alert] %>
            </div>
        <% end %>
      </div>

app/views/shared/_right_side.html.erb
<aside id="rightSide">
    right
</aside>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>